export const filterOptions = {
  type: [
    "",
    "Room",
    "Circulation",
    "Threshold",
    "Zone",
    "Open Space",
    "Technical",
    "Service",
    "Concept",
  ],
  scale: ["", "Interior", "Building", "Site", "Urban"],
  domain: [
    "",
    "Residential",
    "Civic",
    "Religious",
    "Commercial",
    "Industrial",
    "Landscape",
    "Mixed-Use",
    "General",
    "Educational",
  ],
  status: [
    "",
    "Contemporary",
    "Historical",
    "Vernacular",
    "Theoretical",
    "Generic",
  ],
  region: [
    "",
    "Cross-cultural",
    "Global",
    "Islamic",
    "Arab / Islamic",
    "Japanese",
    "Chinese",
    "South Asian",
    "Ottoman / Islamic",
    "Christian ecclesiastical",
    "European",
    "French / European",
    "British / colonial",
    "Modern architectural discourse",
    "Critical spatial theory",
    "General design discourse",
    "Social urban theory",
  ],
  sortBy: ["term", "type", "scale", "domain", "sourceCategory"],
};
